language: go

sudo: false

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

script:
  - go vet
  - go test -v -race -cover
  - ./.travis.quality.sh
  - /Users/vigneshn/Desktop/Golang/bin/gosec -exclude=G104 main.go
  - ./build.sh rebuild
